# Site settings
title: ksdt
email: thollowa@ucsd.edu
description: > # this means to ignore newlines until "baseurl:"
    KSDT
baseurl: "/ksdt-website" # the subpath of your site, e.g. /blog/
url: "https://ksdt.org" # the base hostname & protocol for your site
twitter_username: barontennyson
github_username:  tennysonholloway

# Build settings
markdown: kramdown
