# Site settings
title: 1034b.pw/blog
email: tennyson@fastmail.com
description: > # this means to ignore newlines until "baseurl:"
    Writings by Tennyson Holloway. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: barontennyson
github_username:  tennysonholloway

# Build settings
markdown: kramdown
